extends Node
## Db — static game data: items, classes, enemies, loot, mutations, helpers.
## Autoload. Crafted things (spells/potions/skills) are items with a `meta`
## dict generated by the crafting systems; everything here is JSON-safe.

enum Rarity { COMMON, UNCOMMON, RARE, EPIC, MYTHIC, CURSED }

const RARITY_NAMES := {
	Rarity.COMMON: "Common", Rarity.UNCOMMON: "Uncommon", Rarity.RARE: "Rare",
	Rarity.EPIC: "Epic", Rarity.MYTHIC: "Mythic", Rarity.CURSED: "Cursed",
}
const RARITY_COLORS := {
	Rarity.COMMON: Color(0.8, 0.8, 0.8), Rarity.UNCOMMON: Color(0.4, 0.85, 0.4),
	Rarity.RARE: Color(0.35, 0.6, 1.0), Rarity.EPIC: Color(0.75, 0.4, 0.95),
	Rarity.MYTHIC: Color(1.0, 0.75, 0.2), Rarity.CURSED: Color(0.9, 0.2, 0.3),
}

## kind: block | tool | weapon | rune | card | essence | ingredient | potion |
## spell | skill | cache. block items carry "block" (voxel id), tools "speed",
## weapons "dmg" [count, die, bonus] + "atk", ingredients "props".
const ITEMS := {
	# --- placeable blocks
	"stone": {"name": "Stone", "kind": "block", "block": 2, "stack": 99, "value": 1, "color": Color(0.38, 0.36, 0.42)},
	"dirt": {"name": "Dirt", "kind": "block", "block": 3, "stack": 99, "value": 1, "color": Color(0.35, 0.25, 0.17)},
	"wood": {"name": "Wood", "kind": "block", "block": 4, "stack": 99, "value": 2, "color": Color(0.45, 0.32, 0.18)},
	"brick": {"name": "Dungeon Brick", "kind": "block", "block": 26, "stack": 99, "value": 2, "color": Color(0.28, 0.24, 0.34)},
	"glowstone": {"name": "Glowstone", "kind": "block", "block": 7, "stack": 99, "value": 6, "color": Color(0.95, 0.85, 0.45)},
	"sand": {"name": "Sand", "kind": "block", "block": 14, "stack": 99, "value": 1, "color": Color(0.8, 0.72, 0.5)},
	"gravel": {"name": "Gravel", "kind": "block", "block": 15, "stack": 99, "value": 1, "color": Color(0.5, 0.48, 0.46)},
	"obsidian": {"name": "Obsidian", "kind": "block", "block": 9, "stack": 99, "value": 8, "color": Color(0.16, 0.1, 0.24)},
	"door": {"name": "Door", "kind": "block", "block": 27, "stack": 20, "value": 6, "color": Color(0.55, 0.4, 0.22)},
	"golden_key": {"name": "Golden Key", "kind": "key", "stack": 1, "value": 90, "color": Color(0.95, 0.82, 0.3)},
	"campfire": {"name": "Campfire", "kind": "block", "block": 42, "stack": 5, "value": 25, "color": Color(0.95, 0.6, 0.2)},
	"water_orb": {"name": "Water Orb", "kind": "block", "block": 11, "stack": 10, "value": 12, "color": Color(0.2, 0.35, 0.7)},
	"lava_orb": {"name": "Lava Orb", "kind": "block", "block": 10, "stack": 10, "value": 22, "color": Color(0.95, 0.35, 0.08)},
	"acid_flask": {"name": "Acid Flask", "kind": "block", "block": 35, "stack": 10, "value": 28, "color": Color(0.35, 0.85, 0.15)},
	"seeds": {"name": "Wheat Seeds", "kind": "seed", "stack": 30, "value": 4, "color": Color(0.7, 0.75, 0.4)},
	# --- tools (mining)
	"pick_rusty": {"name": "Rusty Pick", "kind": "tool", "speed": 1.0, "stack": 1, "value": 10, "color": Color(0.5, 0.4, 0.35)},
	"pick_gilded": {"name": "Gilded Pick", "kind": "tool", "speed": 2.2, "stack": 1, "value": 80, "color": Color(0.9, 0.75, 0.3)},
	"pick_mythril": {"name": "Mythril Pick", "kind": "tool", "speed": 4.5, "stack": 1, "value": 300, "color": Color(0.5, 0.85, 0.95)},
	# --- weapons (combat; dmg = [dice count, die size, flat bonus])
	"blade_rusty": {"name": "Rusty Blade", "kind": "weapon", "dmg": [1, 6, 0], "atk": 0, "stack": 1, "value": 15, "color": Color(0.55, 0.5, 0.45)},
	"blade_gilded": {"name": "Gilded Saber", "kind": "weapon", "dmg": [2, 6, 1], "atk": 1, "stack": 1, "value": 110, "color": Color(0.9, 0.75, 0.3)},
	"blade_mythril": {"name": "Mythril Greatblade", "kind": "weapon", "dmg": [3, 6, 2], "atk": 2, "stack": 1, "value": 380, "color": Color(0.5, 0.85, 0.95)},
	"maul_bone": {"name": "Bone Maul", "kind": "weapon", "dmg": [1, 12, 0], "atk": 0, "stack": 1, "value": 60, "color": Color(0.85, 0.8, 0.7)},
	# --- bows (ranged: true → Shoot action in combat, aimed shots + sneak attacks in the world)
	"bow_short": {"name": "Shortbow", "kind": "weapon", "ranged": true, "dmg": [1, 8, 0], "atk": 1, "stack": 1, "value": 45, "color": Color(0.5, 0.38, 0.25)},
	"bow_gilded": {"name": "Gilded Longbow", "kind": "weapon", "ranged": true, "dmg": [2, 6, 1], "atk": 2, "stack": 1, "value": 180, "color": Color(0.9, 0.75, 0.3)},
	"arrow": {"name": "Arrow", "kind": "ammo", "stack": 60, "value": 2, "color": Color(0.7, 0.65, 0.55)},
	# --- armor (slot: head | body; ac adds to base AC; smith quality adds more)
	"cap_hide": {"name": "Hide Cap", "kind": "armor", "slot": "head", "ac": 1, "stack": 1, "value": 20, "color": Color(0.6, 0.45, 0.35)},
	"helm_gilded": {"name": "Gilded Helm", "kind": "armor", "slot": "head", "ac": 2, "stack": 1, "value": 120, "color": Color(0.9, 0.75, 0.3)},
	"armor_hide": {"name": "Hide Jerkin", "kind": "armor", "slot": "body", "ac": 1, "stack": 1, "value": 35, "color": Color(0.55, 0.4, 0.3)},
	"armor_bone": {"name": "Bonecarved Mail", "kind": "armor", "slot": "body", "ac": 2, "stack": 1, "value": 90, "color": Color(0.85, 0.8, 0.7)},
	"armor_gilded": {"name": "Gilded Cuirass", "kind": "armor", "slot": "body", "ac": 3, "stack": 1, "value": 200, "color": Color(0.9, 0.75, 0.3)},
	"armor_obsidian": {"name": "Obsidian Plate", "kind": "armor", "slot": "body", "ac": 4, "stack": 1, "value": 420, "color": Color(0.16, 0.1, 0.24)},
	# --- smithing materials
	"bone": {"name": "Bleached Bone", "kind": "material", "stack": 30, "value": 5, "color": Color(0.88, 0.85, 0.75)},
	"hog_hide": {"name": "Gloom Hog Hide", "kind": "material", "stack": 30, "value": 7, "color": Color(0.5, 0.38, 0.3)},
	# --- spellcrafting runes (world effect)
	"rune_ruin": {"name": "Rune of Ruin", "kind": "rune", "effect": "explode", "stack": 9, "value": 30, "color": Color(0.9, 0.3, 0.2)},
	"rune_greed": {"name": "Rune of Greed", "kind": "rune", "effect": "transmute_gold", "stack": 9, "value": 45, "color": Color(0.95, 0.78, 0.25)},
	"rune_frost": {"name": "Rune of Frost", "kind": "rune", "effect": "ice_path", "stack": 9, "value": 25, "color": Color(0.6, 0.8, 0.95)},
	"rune_flora": {"name": "Rune of Flora", "kind": "rune", "effect": "vines", "stack": 9, "value": 20, "color": Color(0.3, 0.7, 0.3)},
	"rune_ember": {"name": "Rune of Ember", "kind": "rune", "effect": "lava_burst", "stack": 9, "value": 35, "color": Color(0.95, 0.5, 0.1)},
	"rune_fate": {"name": "Rune of Fate", "kind": "rune", "effect": "teleport", "stack": 9, "value": 40, "color": Color(0.6, 0.4, 0.9)},
	"rune_fortune": {"name": "Rune of Fortune", "kind": "rune", "effect": "luck_buff", "stack": 9, "value": 35, "color": Color(0.35, 0.85, 0.55)},
	"rune_veil": {"name": "Rune of Veils", "kind": "rune", "effect": "smoke_cloud", "stack": 9, "value": 30, "color": Color(0.4, 0.4, 0.45)},
	"rune_snare": {"name": "Rune of Snares", "kind": "rune", "effect": "glyph_trap", "stack": 9, "value": 38, "color": Color(0.8, 0.4, 0.3)},
	# --- fate sigils (spell power component; kind kept as "card" for save compat)
	"card_jack": {"name": "Lesser Sigil", "kind": "card", "power": 1, "stack": 9, "value": 15, "color": Color(0.7, 0.7, 0.8)},
	"card_queen": {"name": "Greater Sigil", "kind": "card", "power": 2, "stack": 9, "value": 35, "color": Color(0.8, 0.5, 0.8)},
	"card_king": {"name": "Royal Sigil", "kind": "card", "power": 3, "stack": 9, "value": 70, "color": Color(0.9, 0.7, 0.3)},
	"card_ace": {"name": "Fate Sigil", "kind": "card", "power": 4, "stack": 9, "value": 120, "color": Color(0.95, 0.95, 0.95)},
	"card_joker": {"name": "Wild Sigil", "kind": "card", "power": 0, "stack": 9, "value": 66, "color": Color(0.9, 0.2, 0.5)},
	# --- essences (element → combat trick)
	"ess_ember": {"name": "Ember Essence", "kind": "essence", "element": "ember", "stack": 9, "value": 25, "color": Color(0.95, 0.45, 0.15)},
	"ess_frost": {"name": "Frost Essence", "kind": "essence", "element": "frost", "stack": 9, "value": 25, "color": Color(0.55, 0.8, 0.95)},
	"ess_verdant": {"name": "Verdant Essence", "kind": "essence", "element": "verdant", "stack": 9, "value": 25, "color": Color(0.35, 0.8, 0.4)},
	"ess_void": {"name": "Void Essence", "kind": "essence", "element": "void", "stack": 9, "value": 50, "color": Color(0.3, 0.15, 0.45)},
	"ess_gilded": {"name": "Gilded Essence", "kind": "essence", "element": "gilded", "stack": 9, "value": 40, "color": Color(0.95, 0.8, 0.3)},
	# --- alchemy ingredients (2 props each; shared props become potion effects)
	# "food" props feed the cooking system the same way (see crafting/cooking.gd).
	"luckroot": {"name": "Luckroot", "kind": "ingredient", "props": ["luck", "heal"], "food": ["fortune", "hearty"], "tier": 1, "stack": 20, "value": 8, "color": Color(0.45, 0.9, 0.5)},
	"gloomcap": {"name": "Gloomcap", "kind": "ingredient", "props": ["heal", "toxic"], "food": ["iron", "hearty"], "tier": 1, "stack": 20, "value": 8, "color": Color(0.55, 0.4, 0.75)},
	"cinder_bloom": {"name": "Cinder Bloom", "kind": "ingredient", "props": ["volatile", "swift"], "food": ["strength", "iron"], "tier": 1, "stack": 20, "value": 10, "color": Color(0.95, 0.5, 0.25)},
	"gold_dust": {"name": "Gold Dust", "kind": "ingredient", "props": ["luck", "volatile"], "food": ["fortune", "fortune"], "tier": 2, "stack": 20, "value": 15, "color": Color(0.95, 0.85, 0.4)},
	"marrow_dust": {"name": "Marrow Dust", "kind": "ingredient", "props": ["stone", "toxic"], "food": ["iron", "strength"], "tier": 2, "stack": 20, "value": 14, "color": Color(0.85, 0.8, 0.7)},
	"quicksilver": {"name": "Quicksilver", "kind": "ingredient", "props": ["swift", "volatile"], "tier": 2, "stack": 20, "value": 18, "color": Color(0.75, 0.78, 0.85)},
	"gilded_moss": {"name": "Gilded Moss", "kind": "ingredient", "props": ["luck", "stone"], "food": ["fortune", "iron"], "tier": 2, "stack": 20, "value": 16, "color": Color(0.75, 0.8, 0.35)},
	"luck_shard": {"name": "Luck Shard", "kind": "ingredient", "props": ["luck", "luck"], "food": ["fortune", "fortune"], "tier": 3, "stack": 20, "value": 30, "color": Color(0.3, 0.9, 0.6)},
	# --- foods (cooking-only ingredients; grown, hunted, or gathered)
	"wheat": {"name": "Dungeon Wheat", "kind": "ingredient", "props": ["heal", "heal"], "food": ["hearty", "fortune"], "tier": 1, "stack": 30, "value": 6, "color": Color(0.85, 0.78, 0.35)},
	"hog_meat": {"name": "Gloom Hog Meat", "kind": "ingredient", "props": ["heal", "stone"], "food": ["hearty", "strength"], "tier": 2, "stack": 20, "value": 12, "color": Color(0.8, 0.45, 0.45)},
	"toad_leg": {"name": "Luck Toad Leg", "kind": "ingredient", "props": ["luck", "swift"], "food": ["fortune", "strength"], "tier": 2, "stack": 20, "value": 14, "color": Color(0.5, 0.8, 0.45)},
	"moth_egg": {"name": "Dust Moth Egg", "kind": "ingredient", "props": ["heal", "swift"], "food": ["strength", "fortune"], "tier": 2, "stack": 20, "value": 12, "color": Color(0.9, 0.88, 0.75)},
	"kelp": {"name": "Gloamkelp", "kind": "ingredient", "props": ["gills", "heal"], "food": ["hearty", "iron"], "tier": 2, "stack": 20, "value": 10, "color": Color(0.25, 0.6, 0.5)},
	"sootcap": {"name": "Sootcap", "kind": "ingredient", "props": ["smoke", "toxic"], "tier": 1, "stack": 20, "value": 9, "color": Color(0.3, 0.28, 0.3)},
	# --- crafted / generated (meta carries the payload)
	"potion": {"name": "Potion", "kind": "potion", "stack": 5, "value": 20, "color": Color(0.6, 0.3, 0.8)},
	"spell": {"name": "Spell", "kind": "spell", "stack": 1, "value": 60, "color": Color(0.5, 0.3, 0.9)},
	"skill": {"name": "Skill Scroll", "kind": "skill", "stack": 1, "value": 80, "color": Color(0.9, 0.6, 0.3)},
	"gambit_cache": {"name": "Treasure Cache", "kind": "cache", "stack": 5, "value": 100, "color": Color(0.95, 0.7, 0.2)},
}

## Use-leveled disciplines. Effective level = use level + allocated points × 2.
const PROFS := ["combat", "mining", "smithing", "alchemy", "cooking", "spellcraft", "enchanting"]

## Blacksmithing recipes (Skyrim-style: materials in, gear out; quality scales
## with the smith's effective level). mats = {item_id: count}.
const SMITH_RECIPES := [
	{"id": "blade_rusty", "mats": {"stone": 3, "wood": 2}, "lvl": 1},
	{"id": "cap_hide", "mats": {"hog_hide": 3}, "lvl": 1},
	{"id": "armor_hide", "mats": {"hog_hide": 5}, "lvl": 3},
	{"id": "maul_bone", "mats": {"bone": 4, "wood": 1}, "lvl": 5},
	{"id": "armor_bone", "mats": {"bone": 6, "hog_hide": 2}, "lvl": 8},
	{"id": "blade_gilded", "mats": {"gold_dust": 4, "wood": 2}, "lvl": 10},
	{"id": "helm_gilded", "mats": {"gold_dust": 4}, "lvl": 12},
	{"id": "armor_gilded", "mats": {"gold_dust": 6, "hog_hide": 2}, "lvl": 12},
	{"id": "blade_mythril", "mats": {"obsidian": 4, "luck_shard": 2}, "lvl": 20},
	{"id": "armor_obsidian", "mats": {"obsidian": 6}, "lvl": 22},
	{"id": "arrow", "mats": {"wood": 1, "stone": 1}, "lvl": 1, "count": 8},
	{"id": "bow_short", "mats": {"wood": 4, "hog_hide": 1}, "lvl": 3},
	{"id": "bow_gilded", "mats": {"gold_dust": 4, "wood": 3, "hog_hide": 1}, "lvl": 14},
]
const QUALITY_PREFIX := ["", "Fine ", "Superior ", "Exquisite ", "Legendary "]

## Enchanting: essence + gear at the Enchanting Altar. Weapon and armor
## enchants differ; power scales with the enchanter's effective level.
const ENCH_WEAPON := {
	"ember": {"name": "Flamebrand", "desc": "+1d4 fire per power on hit"},
	"frost": {"name": "Frostbite", "desc": "chance per power to freeze the foe's turn"},
	"void": {"name": "Souleater", "desc": "+1d4 dark, drink 2 HP per power on hit"},
	"gilded": {"name": "Goldtouched", "desc": "+10 gold per power on kill"},
	"verdant": {"name": "Thornheart", "desc": "heal 1 per power on hit"},
}
const ENCH_ARMOR := {
	"ember": {"name": "Bulwark", "desc": "+1 AC per power"},
	"frost": {"name": "Tideborn", "desc": "breathe underwater"},
	"void": {"name": "Dread", "desc": "-1 foe attack per power"},
	"gilded": {"name": "Fortunate", "desc": "+4 luck per power"},
	"verdant": {"name": "Mending", "desc": "heal 3 per power after each victory"},
}

## Class combat stats: atk (to-hit bonus), def (added to base AC 10),
## dmg (unarmed dice) — a found weapon overrides dmg and adds its atk.
const CLASSES := {
	"cardsharp": {"name": "Shadowblade Rogue", "hp": 90, "luck": 20, "gold": 80,
		"atk": 3, "def": 2, "dmg": [1, 4, 1],
		"color": Color(0.6, 0.3, 0.7), "desc": "Reads every tell. Starts with Seer's Brand (hex spell)."},
	"rune_dealer": {"name": "Runesmith", "hp": 100, "luck": 15, "gold": 60,
		"atk": 2, "def": 1, "dmg": [1, 4, 0],
		"color": Color(0.35, 0.5, 0.9), "desc": "Starts with spellcrafting reagents."},
	"high_roller": {"name": "Vault Crusader", "hp": 120, "luck": 10, "gold": 150,
		"atk": 2, "def": 3, "dmg": [1, 6, 0],
		"color": Color(0.95, 0.8, 0.3), "desc": "Armored and rich. Silver Tongue passive: +15% gold from kills."},
	"chaos_croupier": {"name": "Chaos Warlock", "hp": 80, "luck": 30, "gold": 40,
		"atk": 3, "def": 0, "dmg": [1, 4, 0],
		"color": Color(0.9, 0.25, 0.45), "desc": "All chaos. Starts with a Wild Sigil and a volatile potion."},
	"soul_banker": {"name": "Soul Warden", "hp": 140, "luck": 5, "gold": 100,
		"atk": 1, "def": 2, "dmg": [1, 8, 0],
		"color": Color(0.4, 0.4, 0.5), "desc": "Soul Strike passive: critical hits land 50% harder."},
	"lucky_bard": {"name": "Fortune Bard", "hp": 100, "luck": 25, "gold": 70,
		"atk": 2, "def": 1, "dmg": [1, 4, 0],
		"color": Color(0.3, 0.85, 0.6), "desc": "Digs up fortune — luck-on-mining passive."},
}

## Base skill metas — class starts, loot, and skill-forge fodder.
## Passives: mine_speed (mult), luck_dig, insight (see enemy AC/intent),
## reroll (reroll one missed attack per battle), bounty (0-1 gold bonus),
## loot_bonus (0-1), soul_strike (bonus crit multiplier).
const BASE_SKILLS := {
	"prospector": {"name": "Prospector", "rarity": Rarity.COMMON, "passives": {"mine_speed": 1.35}},
	"gamblers_eye": {"name": "Seer's Eye", "rarity": Rarity.UNCOMMON, "passives": {"insight": 1.0}},
	"loaded_dice": {"name": "Weighted Fate", "rarity": Rarity.UNCOMMON, "passives": {"reroll": 1.0}},
	"house_edge": {"name": "Silver Tongue", "rarity": Rarity.RARE, "passives": {"bounty": 0.15}},
	"magnet_palms": {"name": "Magnet Palms", "rarity": Rarity.RARE, "passives": {"loot_bonus": 0.25}},
	"lucky_step": {"name": "Lucky Step", "rarity": Rarity.COMMON, "passives": {"luck_dig": 1.0}},
	"soul_channel": {"name": "Soul Channel", "rarity": Rarity.RARE, "passives": {"soul_strike": 0.5}},
}

## Mob roster. disposition: hostile (stalks and fights), neutral (talk / trade /
## rob — turns hostile if provoked), passive (huntable animal, drops food).
## dmg = [count, die, bonus]. special fires on spec_chance each enemy turn:
## multiattack | poison | luck_drain | gold_steal | heal_self | curse.
## shape/size drive the 3D look. min_floor gates the spawn pool (difficulty curve).
const ENEMIES := {
	"gloom_rat": {"name": "Gloom Rat", "hp": 22, "ac": 11, "atk": 2, "dmg": [1, 4, 0],
		"xp": 14, "special": "", "spec_chance": 0.0, "min_floor": 1, "boss": false,
		"shape": "sphere", "size": 0.55, "color": Color(0.45, 0.4, 0.5)},
	"rattlebone": {"name": "Rattlebone Skeleton", "hp": 32, "ac": 12, "atk": 3, "dmg": [1, 6, 1],
		"xp": 22, "special": "", "spec_chance": 0.0, "min_floor": 1, "boss": false,
		"drops": [{"id": "bone", "count": 2}],
		"shape": "tall", "size": 1.0, "color": Color(0.85, 0.82, 0.72)},
	"cave_imp": {"name": "Cave Imp", "hp": 26, "ac": 13, "atk": 3, "dmg": [1, 4, 1],
		"xp": 24, "special": "gold_steal", "spec_chance": 0.3, "min_floor": 1, "boss": false,
		"shape": "capsule", "size": 0.7, "color": Color(0.8, 0.35, 0.25)},
	"gloom_slime": {"name": "Gloom Slime", "hp": 40, "ac": 9, "atk": 2, "dmg": [1, 6, 0],
		"xp": 20, "special": "poison", "spec_chance": 0.35, "min_floor": 2, "boss": false,
		"shape": "blob", "size": 0.9, "color": Color(0.45, 0.3, 0.65)},
	"dice_golem": {"name": "Rune Golem", "hp": 60, "ac": 14, "atk": 4, "dmg": [1, 8, 1],
		"xp": 40, "special": "multiattack", "spec_chance": 0.3, "min_floor": 3, "boss": false,
		"shape": "box", "size": 1.1, "color": Color(0.88, 0.88, 0.92)},
	"vault_wraith": {"name": "Vault Wraith", "hp": 48, "ac": 15, "atk": 5, "dmg": [2, 4, 0],
		"xp": 48, "special": "luck_drain", "spec_chance": 0.35, "min_floor": 4, "boss": false,
		"shape": "tall", "size": 1.15, "color": Color(0.5, 0.75, 0.85)},
	"cursed_croupier": {"name": "Cursed Hexer", "hp": 55, "ac": 13, "atk": 5, "dmg": [1, 10, 1],
		"xp": 55, "special": "curse", "spec_chance": 0.3, "min_floor": 5, "boss": false,
		"shape": "capsule", "size": 1.0, "color": Color(0.65, 0.2, 0.4)},
	"obsidian_brute": {"name": "Obsidian Brute", "hp": 85, "ac": 12, "atk": 5, "dmg": [2, 8, 2],
		"xp": 70, "special": "heal_self", "spec_chance": 0.2, "min_floor": 6, "boss": false,
		"shape": "box", "size": 1.35, "color": Color(0.2, 0.13, 0.3)},
	"coin_bat": {"name": "Coin Bat", "hp": 18, "ac": 14, "atk": 3, "dmg": [1, 4, 0],
		"xp": 18, "special": "gold_steal", "spec_chance": 0.4, "min_floor": 2, "boss": false,
		"shape": "sphere", "size": 0.45, "color": Color(0.75, 0.65, 0.3)},
	"mimic": {"name": "Mimic", "hp": 50, "ac": 13, "atk": 5, "dmg": [2, 6, 1],
		"xp": 55, "special": "multiattack", "spec_chance": 0.25, "min_floor": 3, "boss": false,
		"shape": "box", "size": 0.9, "color": Color(0.7, 0.45, 0.15)},
	"tomb_howler": {"name": "Tomb Howler", "hp": 58, "ac": 14, "atk": 5, "dmg": [1, 8, 2],
		"xp": 60, "special": "curse", "spec_chance": 0.35, "min_floor": 5, "boss": false,
		"shape": "tall", "size": 1.2, "color": Color(0.35, 0.3, 0.45)},
	# --- oozes (D&D style)
	"acid_cube": {"name": "Gelatinous Cube", "hp": 75, "ac": 7, "atk": 3, "dmg": [2, 6, 0],
		"xp": 65, "special": "engulf", "spec_chance": 0.3, "min_floor": 3, "boss": false,
		"shape": "box", "size": 1.5, "color": Color(0.55, 0.9, 0.6)},
	"black_pudding": {"name": "Black Pudding", "hp": 60, "ac": 9, "atk": 4, "dmg": [1, 10, 1],
		"xp": 62, "special": "acid_spit", "spec_chance": 0.35, "min_floor": 5, "boss": false,
		"shape": "blob", "size": 1.2, "color": Color(0.1, 0.08, 0.12)},
	"ochre_jelly": {"name": "Ochre Jelly", "hp": 45, "ac": 8, "atk": 3, "dmg": [1, 8, 0],
		"xp": 45, "special": "split", "spec_chance": 1.0, "min_floor": 4, "boss": false,
		"shape": "blob", "size": 1.0, "color": Color(0.8, 0.6, 0.2)},
	"pit_boss": {"name": "The Vault Tyrant", "hp": 300, "ac": 15, "atk": 6, "dmg": [2, 6, 2],
		"xp": 250, "special": "multiattack", "spec_chance": 0.25, "min_floor": 1, "boss": true,
		"shape": "capsule", "size": 1.8, "color": Color(0.9, 0.2, 0.25)},
	# --- passive animals (E = hunt; instant drops, no combat)
	"gloom_hog": {"name": "Gloom Hog", "hp": 10, "ac": 8, "atk": 0, "dmg": [1, 2, 0],
		"xp": 6, "special": "", "spec_chance": 0.0, "min_floor": 1, "boss": false,
		"disposition": "passive", "drops": [{"id": "hog_meat", "count": 2}, {"id": "hog_hide", "count": 2}],
		"shape": "blob", "size": 0.8, "color": Color(0.6, 0.45, 0.5)},
	"luck_toad": {"name": "Luck Toad", "hp": 8, "ac": 10, "atk": 0, "dmg": [1, 2, 0],
		"xp": 6, "special": "", "spec_chance": 0.0, "min_floor": 1, "boss": false,
		"disposition": "passive", "drops": [{"id": "toad_leg", "count": 1}, {"id": "luckroot", "count": 1}],
		"shape": "blob", "size": 0.55, "color": Color(0.45, 0.85, 0.4)},
	"dust_moth": {"name": "Dust Moth", "hp": 6, "ac": 12, "atk": 0, "dmg": [1, 2, 0],
		"xp": 5, "special": "", "spec_chance": 0.0, "min_floor": 2, "boss": false,
		"disposition": "passive", "drops": [{"id": "moth_egg", "count": 2}],
		"shape": "sphere", "size": 0.4, "color": Color(0.85, 0.83, 0.7)},
	# --- neutral folk (E = talk / trade / rob; provoke them and they fight)
	"lost_explorer": {"name": "Lost Explorer", "hp": 60, "ac": 13, "atk": 4, "dmg": [1, 8, 1],
		"xp": 45, "special": "heal_self", "spec_chance": 0.2, "min_floor": 1, "boss": false,
		"disposition": "neutral", "guard": 12,
		"trades": ["seeds", "campfire", "luckroot", "blade_rusty", "golden_key", "water_orb"],
		"shape": "capsule", "size": 1.0, "color": Color(0.45, 0.6, 0.5)},
	"refuge_citizen": {"name": "Refuge Citizen", "hp": 40, "ac": 11, "atk": 2, "dmg": [1, 4, 0],
		"xp": 20, "special": "", "spec_chance": 0.0, "min_floor": 0, "boss": false,
		"disposition": "neutral", "guard": 9,
		"trades": ["seeds", "wheat", "gloomcap", "campfire", "door"],
		"shape": "capsule", "size": 0.95, "color": Color(0.6, 0.55, 0.7)},
}

## Elite modifiers rolled at spawn — prefix + stat tweaks.
const ELITES := {
	"gilded": {"name": "Gilded", "hp": 1.4, "atk": 0, "ac": 1, "gold": 3.0, "color": Color(0.95, 0.8, 0.3)},
	"cursed": {"name": "Cursed", "hp": 1.2, "atk": 2, "ac": 0, "gold": 1.5, "color": Color(0.85, 0.2, 0.35)},
	"ancient": {"name": "Ancient", "hp": 1.8, "atk": 1, "ac": 2, "gold": 2.0, "color": Color(0.6, 0.85, 0.7)},
}

const MUTATIONS := {
	"golden_touch": {"name": "Golden Touch", "desc": "Mined stone sometimes pays gold."},
	"glass_bones": {"name": "Glass Bones", "desc": "+15 luck, -20 max HP."},
	"third_eye": {"name": "Third Eye", "desc": "See every foe's defenses and intent."},
	"echo_hands": {"name": "Echo Hands", "desc": "Mine 50% faster."},
	"die_hard": {"name": "Die Hard", "desc": "Survive one fatal blow per floor."},
	"loaded_soul": {"name": "Loaded Soul", "desc": "Critical hits land 50% harder."},
	"cursed_veins": {"name": "Cursed Veins", "desc": "+10 luck, gold gains -25%."},
	"magnet_fingers": {"name": "Magnet Fingers", "desc": "+25% loot from kills."},
}


func item_def(id: String) -> Dictionary:
	return ITEMS.get(id, {"name": id, "kind": "junk", "stack": 1, "value": 1, "color": Color.GRAY})


## Display name for an inventory entry {"id", "count", "meta"}.
func item_name(entry: Dictionary) -> String:
	var meta: Dictionary = entry.get("meta", {})
	if meta.has("name"):
		return meta.name
	return item_def(entry.id).name


func item_color(entry: Dictionary) -> Color:
	var meta: Dictionary = entry.get("meta", {})
	if meta.has("rarity"):
		return RARITY_COLORS.get(int(meta.rarity), Color.GRAY)
	return item_def(entry.id).color


func xp_for_level(level: int) -> int:
	return level * 100


# ---------------------------------------------------------------- proficiencies

func new_profs() -> Dictionary:
	var out := {}
	for s in PROFS:
		out[s] = {"xp": 0, "lvl": 1}
	return out


func prof_xp_needed(lvl: int) -> int:
	return lvl * 20


## Effective discipline level: use-earned level + allocated skill points × 2.
func prof_eff(rec: Dictionary, skill: String) -> int:
	var p: Dictionary = rec.get("prof", {}).get(skill, {"lvl": 1})
	return int(p.get("lvl", 1)) + int(rec.get("alloc", {}).get(skill, 0)) * 2


func quality_prefix(q: int) -> String:
	return QUALITY_PREFIX[clampi(q, 0, QUALITY_PREFIX.size() - 1)]


func apply_mutation(rec: Dictionary, mid: String) -> void:
	if mid in rec.mutations:
		return
	rec.mutations.append(mid)
	match mid:
		"glass_bones":
			rec.luck += 15
			rec.max_hp = maxi(rec.max_hp - 20, 30)
			rec.hp = mini(rec.hp, rec.max_hp)
		"cursed_veins":
			rec.luck += 10
		"third_eye":
			rec.passives["insight"] = 1.0
		"echo_hands":
			rec.passives["mine_speed"] = rec.passives.get("mine_speed", 1.0) + 0.5
		"loaded_soul":
			rec.passives["soul_strike"] = maxf(float(rec.passives.get("soul_strike", 0.0)), 0.5)
		"magnet_fingers":
			rec.passives["loot_bonus"] = rec.passives.get("loot_bonus", 0.0) + 0.25


## Weighted enemy type for a floor: the pool grows as you descend (curve),
## and high adaptive threat leans the weights toward the nastier end.
func pick_enemy_type(rng: RandomNumberGenerator, fnum: int, threat: float) -> String:
	var pool: Array = []
	for id in ENEMIES:
		var def: Dictionary = ENEMIES[id]
		if def.boss or fnum < int(def.min_floor):
			continue
		if String(def.get("disposition", "hostile")) != "hostile":
			continue
		# Newer (higher min_floor) types get heavier weights when threat is high.
		var w := 3.0 + float(def.min_floor) * (threat - 0.8) * 2.0
		pool.append({"id": id, "w": maxf(w, 0.5)})
	var total := 0.0
	for p in pool:
		total += p.w
	var r := rng.randf() * total
	for p in pool:
		r -= p.w
		if r <= 0.0:
			return p.id
	return "gloom_rat"


## Random passive/neutral mob eligible for this floor.
func pick_ambient_type(rng: RandomNumberGenerator, fnum: int) -> String:
	var pool: Array = []
	for id in ENEMIES:
		var def: Dictionary = ENEMIES[id]
		var disp := String(def.get("disposition", "hostile"))
		if disp == "hostile" or def.boss or fnum < int(def.min_floor):
			continue
		if id == "refuge_citizen" and fnum != 0:
			continue
		pool.append(id)
	if pool.is_empty():
		return ""
	return pool[rng.randi_range(0, pool.size() - 1)]


## Loot roll on enemy defeat / chest / cache. Returns Array of inventory entries.
func roll_loot(rng: RandomNumberGenerator, fnum: int, luck: int, bonus := 0.0) -> Array:
	var out: Array = []
	var rolls := 2 + (1 if rng.randf() < 0.3 + bonus else 0)
	for i in range(rolls):
		var r := rng.randf() - luck * 0.002 - fnum * 0.01 - bonus * 0.1
		if r < 0.04:
			out.append({"id": "gambit_cache", "count": 1, "meta": {}})
		elif r < 0.10:
			var sid: String = BASE_SKILLS.keys()[rng.randi_range(0, BASE_SKILLS.size() - 1)]
			out.append({"id": "skill", "count": 1, "meta": BASE_SKILLS[sid].duplicate(true)})
		elif r < 0.20:
			var runes := ["rune_ruin", "rune_greed", "rune_frost", "rune_flora", "rune_ember",
				"rune_fate", "rune_fortune", "rune_veil", "rune_snare"]
			out.append({"id": runes[rng.randi_range(0, runes.size() - 1)], "count": 1, "meta": {}})
		elif r < 0.30:
			var cards := ["card_jack", "card_jack", "card_queen", "card_king", "card_ace", "card_joker"]
			out.append({"id": cards[rng.randi_range(0, cards.size() - 1)], "count": 1, "meta": {}})
		elif r < 0.42:
			var ess := ["ess_ember", "ess_frost", "ess_verdant", "ess_void", "ess_gilded"]
			out.append({"id": ess[rng.randi_range(0, ess.size() - 1)], "count": 1, "meta": {}})
		elif r < 0.47:
			var util := ["golden_key", "campfire", "seeds", "door"]
			out.append({"id": util[rng.randi_range(0, util.size() - 1)],
				"count": 3 if util[0] == "seeds" else 1, "meta": {}})
		elif r < 0.52 and fnum >= 2:
			var gear := ["blade_rusty", "maul_bone", "blade_gilded", "cap_hide", "armor_hide", "armor_bone"]
			if fnum >= 6:
				gear.append("blade_mythril")
				gear.append("armor_gilded")
			out.append({"id": gear[rng.randi_range(0, gear.size() - 1)], "count": 1, "meta": {}})
		elif r < 0.60 and fnum >= 4:
			out.append({"id": "pick_gilded" if rng.randf() < 0.8 else "pick_mythril", "count": 1, "meta": {}})
		else:
			var ing := ["luckroot", "gloomcap", "cinder_bloom", "gold_dust", "marrow_dust",
				"quicksilver", "gilded_moss", "bone", "hog_hide", "kelp"]
			out.append({"id": ing[rng.randi_range(0, ing.size() - 1)], "count": rng.randi_range(1, 3), "meta": {}})
	return out


## Deterministic shop stock for a floor: Array of {"id","meta","price"}.
func shop_stock(run_seed: int, fnum: int) -> Array:
	var rng := RandomNumberGenerator.new()
	rng.seed = hash("%d:shop:%d" % [run_seed, fnum])
	var pool := ["rune_ruin", "rune_fortune", "rune_frost", "rune_fate", "card_jack",
		"card_queen", "card_king", "ess_ember", "ess_gilded", "ess_verdant",
		"luckroot", "quicksilver", "gilded_moss", "pick_gilded", "gambit_cache",
		"glowstone", "blade_rusty", "blade_gilded", "maul_bone", "door", "golden_key",
		"campfire", "seeds", "seeds", "water_orb", "acid_flask", "wheat",
		"bone", "hog_hide", "kelp", "armor_hide", "cap_hide",
		"bow_short", "arrow", "arrow", "sootcap", "rune_veil", "rune_snare"]
	var stock: Array = []
	for i in range(8):
		var id: String = pool[rng.randi_range(0, pool.size() - 1)]
		var price := int(item_def(id).value * (1.4 + fnum * 0.08))
		stock.append({"id": id, "meta": {}, "price": price})
	return stock
